name: secrets

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger

jobs:
  login_hudl:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install selenium python-dotenv

      - name: run selenium script
        env:
          HUDL_EMAIL: ${{ secrets.HUDL_EMAIL }}
          HUDL_PASSWORD: ${{ secrets.HUDL_PASSWORD }}
          HUDL_WRONG_EMAIL: ${{ secrets.HUDL_WRONG_EMAIL }}
          HUDL_WRONG_PASSWORD: ${{ secrets.HUDL_WRONG_PASSWORD }}
        run: python user_login.py
